name: Security Analysis

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch:

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  provenance:
    name: check package provenance
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: check provenance downgrades
        uses: danielroe/provenance-action@41bcc969e579d9e29af08ba44fcbfdf95cee6e6c # v0.1.1
        with:
          fail-on-provenance-change: true
          fail-on-downgrade: true

  workflow-security:
    name: workflow security analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: check for workflow changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            workflows:
              - '.github/workflows/**'

      - name: install uv
        if: steps.changes.outputs.workflows == 'true'
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5

      - name: run zizmor
        if: steps.changes.outputs.workflows == 'true'
        run: uvx zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload sarif file
        if: steps.changes.outputs.workflows == 'true'
        uses: github/codeql-action/upload-sarif@c43362b91a940600cde2ebae39ec7a35ad66bdc0 # codeql-bundle-v2.23.8
        with:
          sarif_file: results.sarif
          category: zizmor
