name: cleanup cache

on:
  schedule:
    - cron: "0 11 * * *" # runs every day at 11:00 UTC
  workflow_dispatch:
    inputs:
      max-age:
        description: 'Maximum age of caches to keep (in seconds)'
        required: false
        default: '432000' # 5 days
      mode:
        description: 'Cleanup mode (normal, ref, or all)'
        required: false
        default: 'normal'
      ref-key:
        description: 'Reference key (only for ref mode)'
        required: false
        default: ''
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'
  pull_request:
    types:
      - closed

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    if: github.repository == 'ucdjs/ucd'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: cleanup caches older than 5 days
        uses: luxass/purge-action-cache@8203fbc1edd23369505f170a1d54074195a59c58 # v0.3.0
        with:
          max-age: ${{ github.event_name == 'pull_request' && 0 || github.event.inputs.max-age || 432000 }}
          mode: ${{ github.event_name == 'pull_request' && 'normal' || (github.event.inputs.mode || 'normal') }}
          ref-key: ${{ github.event_name == 'pull_request' && format('refs/pull/{0}/merge', github.event.pull_request.number) || (github.event.inputs.ref-key || '') }}
          debug: ${{ github.event.inputs.debug || 'false' }}


